### ISSUE TITLE
再設計-Rebuild

### ISSUE THREAD

**Issue by Marusoftware** [Marusoftware/Marutools#1]
Marutoolsの再設計について。

**Comment by Marusoftware** [comment]
- Marutoolsコア改修
Butterflyベースに切り替え。
- 構成ソフト再設計
Marueditor
Maruplayer
Marubrowser(Maruplayerと統合？)
Maruconvertor
etc...
- アドオン再設計
せめて動くようにする。

**Comment by Marusoftware** [comment]
share, share_os 削除
butterfly経由のpython pipコントロールにより代用
設定及び他言語対応、アドオンについても同様。

**Comment by maru0123-2004** [comment]
Almost done...
